build() {
	build_pkg libxfce4util
	build_pkg dbus-glib
	build_pkg xfconf
	build_pkg libxfce4ui
	build_pkg URI
	build_pkg exo
	build_pkg garcon
	build_pkg gtk-xfce-engine
	build_pkg libwnck
	build_pkg xfce4-panel
	build_pkg hicolor-icon-theme
	build_pkg XML-Simple
	build_pkg icon-naming-utils
	build_pkg at-spi2-core
	build_pkg at-spi2-atk
	build_pkg gtk3
	build_pkg Thunar
	build_pkg xfdesktop
	build_pkg xfwm4
	build_pkg xfce4-session
	build_pkg terminator
	build_pkg libcroco
	build_pkg vala
	build_pkg librsvg
	build_pkg adwaita-icon-theme
}
