build() {
	build_pkg util-macros
	build_pkg xorgproto
	build_pkg libXau
	build_pkg libXdmcp
	build_pkg xcb-proto
	build_pkg libxcb
	build_pkg xcb-util
	build_pkg xcb-util-image
	build_pkg xcb-util-keysym
	build_pkg xcb-util-renderutil
	build_pkg xcb-util-wm
	build_pkg freetype
	build_pkg fontconfig
	build_pkg xorg-libs
	build_pkg libdrm
	build_pkg Python
	build_pkg Beaker
	build_pkg MarkupSafe
	build_pkg Mako
	build_pkg libuv
	build_pkg libarchive
	build_pkg cmake
	build_pkg llvm
	build_pkg mesa
	build_pkg xbitmaps
	build_pkg libpng
	build_pkg xorg-apps
	build_pkg xcursor-themes
	build_pkg xorg-fonts
	build_pkg xkeyboard-config
	build_pkg pixman
	build_pkg libepoxy
	build_pkg xorg-server
	build_pkg libxml2
}
