build() {
	build_pkg util-macros
	build_pkg xorgproto
	build_pkg libXau
	build_pkg libXdmcp
	build_pkg xcb-proto
	build_pkg libxcb
	build_pkg xcb-util
	build_pkg xcb-util-image
	build_pkg xcb-util-keysym
	build_pkg xcb-util-renderutil
	build_pkg xcb-util-wm
	build_pkg freetype
	build_pkg fontconfig
	build_pkg xorg-libs
	build_pkg libdrm
	build_pkg Python
	build_pkg Beaker
	build_pkg MarkupSafe
	build_pkg Mako
	build_pkg libuv
	build_pkg libarchive
	build_pkg cmake
	build_pkg llvm
	build_pkg mesa
	build_pkg xbitmaps
	build_pkg libpng
	build_pkg xorg-apps
	build_pkg xcursor-themes
	build_pkg xorg-fonts
	build_pkg xkeyboard-config
	build_pkg pixman
	build_pkg libepoxy
	build_pkg xorg-server
	build_pkg libxml2
	build_pkg pcre
	build_pkg which
	build_pkg gobject-introspection
	build_pkg glib
	build_pkg atk
	build_pkg libevdev
	build_pkg mtdev
	build_pkg xf86-input-evdev
	build_pkg twm
	build_pkg nasm
	build_pkg yasm
	build_pkg libjpeg-turbo
	build_pkg shared-mime-info
	build_pkg libtiff
	build_pkg gdk-pixbuf
	build_pkg cairo
	build_pkg fribidi
	build_pkg harfbuzz
	build_pkg pango
	build_pkg gtk+
	build_pkg icu
	build_pkg libsigc++
	build_pkg glibmm
	build_pkg cairomm
	build_pkg pangomm
	build_pkg xf86-video-vesa
	build_pkg xinit
}
